name: Build
on: [ workflow_dispatch, push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 200
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
          cache: gradle
      - uses: gradle/wrapper-validation-action@v3
      - run: chmod +x ./gradlew
      - name: Build with Gradle
        env:
          USERNAME: ${{ secrets.USERNAME }}
          READ_PACKAGES_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}
        run: ./gradlew build
      - name: Check resources
        run: ./gradlew build runDatagen && if [ -n "$(git status --porcelain)" ]; then exit 1; fi
      - name: Publish to Github Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build publish
      - name: Cleanup old artifacts
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'sophisticatedstorage.sophisticatedstorage'
          package-type: 'maven'
          min-versions-to-keep: 10
      - name: Publish to CurseForge
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          if [[ "$BRANCH_NAME" =~ ^[0-9]+\.[0-9]+\.([0-9]+|x)$ ]]; then
            ./gradlew curseforge
          else
            echo "Branch name does not match the pattern: $BRANCH_NAME. Skipping CurseForge upload."
            exit 0
          fi
      - name: Publish to Modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          if [[ "$BRANCH_NAME" =~ ^[0-9]+\.[0-9]+\.([0-9]+|x)$ ]]; then
            ./gradlew modrinth
          else
            echo "Branch name does not match the pattern: $BRANCH_NAME. Skipping Modrinth upload."
            exit 0
          fi