name: Mod Build

on: [ push, workflow_dispatch ]

jobs:
  build:
    strategy:
      matrix:
        java: [17-ubuntu, 21-ubuntu]
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:${{ matrix.java }}
      options: --user root
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v2
      - run: chmod +x ./gradlew
      - name: Build with Gradle
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          READ_PACKAGES_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}
        run: ./gradlew check build publishToMavenLocal --stacktrace --warning-mode=fail -Porg.gradle.parallel.threads=4
      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
      - uses: actions/upload-artifact@v4
        with:
          name: Maven Local
          path: /root/.m2/repository/com/github/salandora
  check_resources:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:17-ubuntu
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: chmod +x ./gradlew
      - env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          READ_PACKAGES_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}
        run: ./gradlew generateResources --stacktrace --warning-mode=fail
      - run: if [ -n "$(git status --porcelain)" ]; then exit 1; fi
